# Generated by Django 6.0.3 on 2026-03-25 12:13

import cloudinary.models
import tourism_events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmedia',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[tourism_events.validators.validate_media_file_type, tourism_events.validators.validate_media_file_size]),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='touristsitemedia',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[tourism_events.validators.validate_media_file_type, tourism_events.validators.validate_media_file_size]),
        ),
        migrations.AlterField(
            model_name='touristsitemedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', editable=False, max_length=10),
        ),
    ]
