# Generated by Django 6.0.3 on 2026-03-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_events', '0002_alter_eventmedia_file_alter_eventmedia_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly URL identifier. Auto-generated from title.', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='touristsite',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly URL identifier. Auto-generated from name.', max_length=255, unique=True),
        ),
    ]
