# Generated by Django 6.0.3 on 2026-03-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_events', '0004_event_date_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='List of package highlights / inclusions shown on the detail page.'),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude of the event venue.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude of the event venue.', max_digits=9, null=True),
        ),
    ]
