# Generated by Django 6.0.3 on 2026-04-01 18:04

import cloudinary.models
import django.db.models.deletion
import tourism_events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_events', '0005_event_highlights_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL identifier. Auto-generated from title.', max_length=255, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('duration', models.CharField(blank=True, help_text='E.g. "3 days / 2 nights", "Full day", "4 hours"', max_length=100)),
                ('price_per_adult', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_per_child', models.DecimalField(decimal_places=2, default=0.0, help_text='Ages 3–12', max_digits=10)),
                ('price_per_infant', models.DecimalField(decimal_places=2, default=0.0, help_text='Under 3', max_digits=10)),
                ('highlights', models.JSONField(blank=True, default=list, help_text='List of tour highlights shown on detail page.')),
                ('inclusions', models.JSONField(blank=True, default=list, help_text='What is included (e.g. meals, transport, guide).')),
                ('exclusions', models.JSONField(blank=True, default=list, help_text='What is NOT included.')),
                ('itinerary', models.JSONField(blank=True, default=list, help_text='Day-by-day itinerary. Each item: {day, title, description}.')),
                ('max_group_size', models.PositiveIntegerField(default=20, help_text='Maximum number of travellers per group.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', editable=False, max_length=10)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, validators=[tourism_events.validators.validate_media_file_type, tourism_events.validators.validate_media_file_size])),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tourism_events.tour')),
            ],
            options={
                'verbose_name': 'Tour Media',
                'verbose_name_plural': 'Tour Media',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=30)),
                ('number_of_adults', models.PositiveIntegerField(default=1)),
                ('number_of_children', models.PositiveIntegerField(default=0, help_text='Ages 3–12')),
                ('number_of_infants', models.PositiveIntegerField(default=0, help_text='Under 3')),
                ('preferred_date', models.DateField()),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_requests', to='tourism_events.tour')),
            ],
            options={
                'verbose_name': 'Trip Request',
                'verbose_name_plural': 'Trip Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
