# Generated by Django 6.0.3 on 2026-04-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_events', '0006_tour_tourmedia_triprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price_per_adult',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price_per_child',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price_per_infant',
        ),
    ]
