# Generated by Django 6.0.3 on 2026-04-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_events', '0007_remove_event_price_remove_tour_price_per_adult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTourRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packages', models.JSONField(default=list, help_text='List of package keys chosen by the customer.')),
                ('number_of_adults', models.PositiveIntegerField(default=1)),
                ('number_of_children', models.PositiveIntegerField(default=0, help_text='Ages 3-12')),
                ('number_of_infants', models.PositiveIntegerField(default=0, help_text='Under 3')),
                ('preferred_start_date', models.DateField(help_text='When the customer wants to start the tour.')),
                ('preferred_end_date', models.DateField(blank=True, help_text='Optional end date for multi-day tours.', null=True)),
                ('flexibility', models.CharField(blank=True, default='exact', help_text='Date flexibility: exact, flexible_1_2_days, flexible_week, anytime', max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sites', models.ManyToManyField(help_text='Tourist sites the customer wants to visit.', related_name='custom_tour_requests', to='tourism_events.touristsite')),
            ],
            options={
                'verbose_name': 'Custom Tour Request',
                'verbose_name_plural': 'Custom Tour Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
