# Generated by Django 6.0.3 on 2026-04-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_events', '0008_customtourrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('corporate', 'Corporate'), ('family', 'Family & Friends'), ('retreat', 'Retreat'), ('recreational', 'Recreational'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=30)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('expected_attendees', models.PositiveIntegerField(default=1, help_text='Estimated number of attendees.')),
                ('location_preference', models.CharField(blank=True, max_length=255)),
                ('budget_range', models.CharField(blank=True, help_text='E.g. "GHS 5,000 – 10,000"', max_length=100)),
                ('activities_interested_in', models.JSONField(blank=True, default=list, help_text='JSON list of activities the customer is interested in.')),
                ('special_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Request',
                'verbose_name_plural': 'Event Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='activities',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of included activities, e.g. ["Drumming", "Dance"].'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('corporate', 'Corporate'), ('family_friends', 'Family & Friends'), ('retreat', 'Retreat'), ('recreational', 'Recreational'), ('cultural', 'Cultural'), ('custom', 'Custom')], default='cultural', help_text='Category / type of event.', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='suitable_for',
            field=models.CharField(blank=True, help_text='Target audience, e.g. "families", "corporate groups".', max_length=255),
        ),
    ]
