# Generated by Django 6.0.3 on 2026-04-03 15:29

import cloudinary.models
import django.db.models.deletion
import tourism_events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_events', '0010_eventbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL identifier. Auto-generated from title.', max_length=255, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('suite', 'Suite')], default='apartment', max_length=20)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('max_guests', models.PositiveIntegerField(default=2)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, help_text='Indicative price per night (GHS).', max_digits=10, null=True)),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of amenities, e.g. ["WiFi", "Pool", "Parking"].')),
                ('rules', models.JSONField(blank=True, default=list, help_text='House rules, e.g. ["No smoking", "No pets"].')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL identifier. Auto-generated from name.', max_length=255, unique=True)),
                ('description', models.TextField()),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van'), ('bus', 'Bus'), ('luxury', 'Luxury')], default='sedan', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_year', models.PositiveIntegerField(blank=True, null=True)),
                ('seats', models.PositiveIntegerField(default=4)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=20)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, help_text='Indicative price per day (GHS).', max_digits=10, null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features, e.g. ["AC", "Bluetooth", "GPS"].')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=30)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('purpose', models.CharField(choices=[('vacation', 'Vacation'), ('business', 'Business'), ('event', 'Event'), ('other', 'Other')], default='vacation', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(blank=True, help_text='Specific apartment, or null for general inquiry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodation_requests', to='tourism_events.apartment')),
            ],
            options={
                'verbose_name': 'Accommodation Request',
                'verbose_name_plural': 'Accommodation Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', editable=False, max_length=10)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, validators=[tourism_events.validators.validate_media_file_type, tourism_events.validators.validate_media_file_size])),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tourism_events.apartment')),
            ],
            options={
                'verbose_name': 'Apartment Media',
                'verbose_name_plural': 'Apartment Media',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarRentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=30)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=255)),
                ('return_location', models.CharField(blank=True, max_length=255)),
                ('with_driver', models.BooleanField(default=False)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, help_text='Specific vehicle, or null for general inquiry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_requests', to='tourism_events.vehicle')),
            ],
            options={
                'verbose_name': 'Car Rental Request',
                'verbose_name_plural': 'Car Rental Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', editable=False, max_length=10)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, validators=[tourism_events.validators.validate_media_file_type, tourism_events.validators.validate_media_file_size])),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tourism_events.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Media',
                'verbose_name_plural': 'Vehicle Media',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
