# Generated by Django 6.0.3 on 2026-04-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_events', '0011_apartment_vehicle_accommodationrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Indicative price per night (GH₵).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('corporate', 'Corporate'), ('family_friends', 'Family & Friends'), ('retreat', 'Retreat'), ('recreational', 'Recreational'), ('cultural', 'Cultural'), ('couples', 'Couples'), ('custom', 'Custom')], default='cultural', help_text='Category / type of event.', max_length=30),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='budget_range',
            field=models.CharField(blank=True, help_text='E.g. "GH₵5,000 – 10,000"', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='event_type',
            field=models.CharField(choices=[('corporate', 'Corporate'), ('family', 'Family & Friends'), ('retreat', 'Retreat'), ('recreational', 'Recreational'), ('couples', 'Couples'), ('custom', 'Custom')], default='custom', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Indicative price per day (GH₵).', max_digits=10, null=True),
        ),
    ]
