# Generated by Django 6.0.3 on 2026-04-03 20:55

import cloudinary.models
import django.db.models.deletion
import tourism_events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_events', '0012_alter_apartment_price_per_night_alter_event_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL. Auto-generated from title.', max_length=255, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, help_text='Date of the project / event.', null=True)),
                ('impact_summary', models.TextField(blank=True, help_text='Short summary of the project community impact.')),
                ('beneficiaries_count', models.PositiveIntegerField(default=0, help_text='Number of people positively impacted.')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Community Project',
                'verbose_name_plural': 'Community Projects',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=255)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('reviewer_photo', cloudinary.models.CloudinaryField(blank=True, help_text='Optional photo of the reviewer.', max_length=255, null=True, verbose_name='reviewer_photo')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating from 1 to 5.')),
                ('title', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('service_type', models.CharField(choices=[('tour', 'Tour'), ('accommodation', 'Accommodation'), ('event', 'Event'), ('car_rental', 'Car Rental'), ('general', 'General')], default='general', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', editable=False, max_length=10)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, validators=[tourism_events.validators.validate_media_file_type, tourism_events.validators.validate_media_file_size], verbose_name='file')),
                ('community_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tourism_events.communityproject')),
            ],
            options={
                'verbose_name': 'Community Project Media',
                'verbose_name_plural': 'Community Project Media',
                'ordering': ['created_at'],
            },
        ),
    ]
