# Generated by Django 6.0.3 on 2026-04-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_events', '0014_site_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('review', 'New Review'), ('trip_request', 'Trip Request'), ('custom_tour_request', 'Custom Tour Request'), ('event_request', 'Event Request'), ('event_booking', 'Event Booking'), ('accommodation_req', 'Accommodation Request'), ('car_rental_req', 'Car Rental Request'), ('system', 'System')], default='system', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text='Frontend admin route to navigate to, e.g. /admin/reviews', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
