# Generated by Django 6.0.3 on 2026-04-14 10:02

import cloudinary.models
import tourism_events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_events', '0015_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsSectionBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Image description/title', max_length=255)),
                ('image', cloudinary.models.CloudinaryField(help_text='Image for events section background cycling', max_length=255, validators=[tourism_events.validators.validate_media_file_type, tourism_events.validators.validate_media_file_size])),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0-indexed). Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Disable to hide from rotation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Events Section Background Image',
                'verbose_name_plural': 'Events Section Background Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Image description/title', max_length=255)),
                ('image', cloudinary.models.CloudinaryField(help_text='Image for hero background slideshow', max_length=255, validators=[tourism_events.validators.validate_media_file_type, tourism_events.validators.validate_media_file_size])),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0-indexed). Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Disable to hide from rotation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Background Image',
                'verbose_name_plural': 'Hero Background Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroMosaic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('cell1', 'Cell 1 - Left column, full height (tall)'), ('cell2', 'Cell 2 - Top right'), ('cell3', 'Cell 3 - Bottom right (tall)')], help_text='Grid position for this image', max_length=10)),
                ('image', cloudinary.models.CloudinaryField(help_text='Image for hero mosaic panel', max_length=255, validators=[tourism_events.validators.validate_media_file_type, tourism_events.validators.validate_media_file_size])),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Mosaic Image',
                'verbose_name_plural': 'Hero Mosaic Images',
                'ordering': ['position'],
                'unique_together': {('position',)},
            },
        ),
    ]
