"""
Django settings for tourism_backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import cloudinary
import cloudinary.uploader
import cloudinary.api

#project_home = 'home/GhanaExperience/tourism/backend'
#load_dotenv(os.path.join(project_home, '.env'))  # Load .env from project root
load_dotenv() #gotta remove this


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-fallback-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'tourism-j3nz.onrender.com',
    'localhost',
    '127.0.0.1',
    #'GhanaExperience.pythonanywhere.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'cloudinary_storage',
    'cloudinary',
    # Local apps
    'app_health_check',
    'tourism_events',
    # Filtering
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',          # Must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tourism_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tourism_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ---------------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------------
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ---------------------------------------------------------------------------
# Media files (local development)
# ---------------------------------------------------------------------------
# In production, Cloudinary handles media uploads (configured below).
# Locally, files land in BASE_DIR/media/ and are served by Django's dev server.

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# ---------------------------------------------------------------------------
# Cloudinary (used as DEFAULT_FILE_STORAGE in production / always)
# ---------------------------------------------------------------------------

cloudinary.config(
    cloud_name=os.getenv('CLOUD_NAME'),
    api_key=os.getenv('API_KEY'),
    api_secret=os.getenv('API_SECRET'),
)

# Use Cloudinary for all media uploads
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUD_NAME'),
    'API_KEY': os.getenv('API_KEY'),
    'API_SECRET': os.getenv('API_SECRET'),
    'MEDIA_TAG': 'tourism_media',            # tag added to every upload
    'INVALID_VIDEO_ERROR_MESSAGE': 'Invalid video format.',
    'EXCLUDE_DELETE_ORPHANED_MEDIA_PATHS': ('tourism/',),
    'PREFIX': 'tourism',                     # folder prefix in Cloudinary
}


# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # ── Authentication ─────────────────────────────────────────────────────
    # JWT Bearer tokens are primary; Session auth is kept so the
    # Django admin / browsable API still work without extra steps.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # ── Default permission: public reads, writes need a valid token ────────
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    # Global filter backends applied to every view
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # Pagination — clients can override with ?page_size=N (max 100)
    'DEFAULT_PAGINATION_CLASS': 'tourism_backend.pagination.StandardPagination',
    'PAGE_SIZE': 10,
}


# ---------------------------------------------------------------------------
# Simple JWT
# ---------------------------------------------------------------------------
from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    # Access tokens expire after 1 day; refresh tokens last 30 days.
    'ACCESS_TOKEN_LIFETIME':  timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),

    # Issue a new refresh token on every /token/refresh call
    # (old one is blacklisted — requires token_blacklist app).
    'ROTATE_REFRESH_TOKENS':  True,
    'BLACKLIST_AFTER_ROTATION': True,

    # Standard Bearer scheme used by all clients
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',

    # Include the token type ("access" / "refresh") in the payload
    'TOKEN_TYPE_CLAIM': 'token_type',

    # Allow sliding-window tokens (optional, disabled by default)
    'SLIDING_TOKEN_LIFETIME':         timedelta(days=1),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=30),

    # Algorithm & keys
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}


# ---------------------------------------------------------------------------
# CORS
# ---------------------------------------------------------------------------

# Base origins that are always allowed
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

# Add the production frontend URL from an environment variable
# Set FRONTEND_URL on Render, e.g. https://tourism-xyz.vercel.app
_frontend_url = os.getenv('FRONTEND_URL', '')
if _frontend_url:
    CORS_ALLOWED_ORIGINS.append(_frontend_url.rstrip('/'))

# Also allow all *.vercel.app preview/production domains + ghanaexperience.xyz
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^https://.*\.vercel\.app$',
    r'^https://(www\.)?ghanaexperience\.xyz$',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# ---------------------------------------------------------------------------
# Default primary key
# ---------------------------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# Logging — ensure email/error logs reach Render console (stdout)
# ---------------------------------------------------------------------------

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'tourism_events.emails': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.core.mail': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# ---------------------------------------------------------------------------
# Email — Resend HTTP API (works on Render which blocks SMTP ports)
# ---------------------------------------------------------------------------

EMAIL_BACKEND       = 'tourism_backend.resend_backend.ResendEmailBackend'
RESEND_API_KEY      = os.getenv('RESEND_API_KEY', '')
DEFAULT_FROM_EMAIL  = os.getenv('DEFAULT_FROM_EMAIL', 'onboarding@resend.dev')

# Company email that receives trip-request notifications
COMPANY_EMAIL       = os.getenv('COMPANY_EMAIL', 'info@1957ghanaexperience.com')

# Company WhatsApp number (international format without +)
COMPANY_WHATSAPP    = os.getenv('COMPANY_WHATSAPP', '233557533568')

# Logo URL for branded emails (hosted on Cloudinary)
LOGO_URL            = os.getenv(
    'LOGO_URL',
    'https://res.cloudinary.com/dy8me66pj/image/upload/v1775072991/tourism/branding/logo.png',
)

# Frontend URL (used for admin links in emails)
FRONTEND_URL        = os.getenv('FRONTEND_URL', 'http://localhost:3000')